{
  "headers": {
    "client_id": "6594903a87af44d980d2421f5c3a24d8",
    "client_secret": "6a39DAdba8514e1D9b48B75Da1D55Ae2",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.32.3",
    "accept": "*/*",
    "postman-token": "dd5fab8d-ae88-4832-813e-0d4de17a768b",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "221"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "https",
  "queryParams": {},
  "requestUri": "/api/pro-addComplaint",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/pro-addComplaint",
  "listenerPath": "/api/*",
  "relativePath": "/api/pro-addComplaint",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/pro-addComplaint",
  "rawRequestPath": "/api/pro-addComplaint",
  "remoteAddress": "/127.0.0.1:63381",
  "requestPath": "/api/pro-addComplaint"
}